### ISSUE TITLE
warmup_fn phase,DataLoader worker (pid 971351) is killed by signal: Segmentation fault

### ISSUE THREAD

**Issue by halozyb** [Matrix-ASC/DeLA#12]
Hello teacher, thank you for exposing your code. Can this code be used for semantic segmentation of airborne point clouds? For example, Toronto3d, I couldn't do it for a long time, and I got a Segmentation fault in the warmup_fn phase, whereas with the same code, I was able to train on a small-scale S3DIS dataset. Thank you

**Comment by binjiechen** [comment]
Hi, the segmentation fault is most likely caused by the c++ grid subsampling function. As the default hyper parameters are set for S3DIS, some adjustments are necessary for another dataset.
1. The default grid_size is 0.04 (in config.py). It is the input resolution, i.e., point cloud is first subsampled to this resolution before sent to network. I'm not familiar with Toronto3d. But at their [repo](https://github.com/WeikaiTan/Toronto-3D), they mentioned using 6cm (0.06) for grid subsampling. So you can set 0.06, 0.12, 0.24, 0.48. grid size for s3dis_warmup_args is used for warmup (so GPU memory is pre-allocated finely), and the parameters are the lower bound of downsampling ratio. The default is normally fine.
2. In line 74, 76 of s3dis.py, set the third argument to estimated downsampling ratio (default is 2.5 / 14), which is 2.5 / (original point cloud size / sampled point cloud size). You can simply set this to 1. It only slightly affects memory used and processing time.
3. Then, the cor_std in config.py. It is the normalizing coefficient for relative coordinates prediction regularization. You can uncomment line 195 of delasemseg.py and comment line 194. Run some iterations. It will print the standard of relative coordinates for each stage. Comment back the code after setting cor_std. One thing to note is that the order is reversed, i.e., the standard for last stage is print first.
4. Set num_classes in line 35 of config.py and line 70 of train.py.
5. For best performance, set max_pts (maximum points per scene during training) in config,  loop in line 46 of train.py. epoch x loop = total epoches. And other hyper parameters such as data augmentation (you can check out other works for best practice).

Hope you find this helpful.

**Comment by halozyb** [comment]
Thank you for your reply. I was busy with other work for a while and didn't have the chance to properly address this issue. Now, following your advice, I've made the necessary modifications and have successfully resolved the problem. I am truly grateful for your excellent work.
