### ISSUE TITLE
The hash_size in grid_subsampling

### ISSUE THREAD

**Issue by HaoRan-hash** [Matrix-ASC/DeLA#4]
<img width="470" alt="屏幕截图 2023-10-20 161300" src="https://github.com/Matrix-ASC/DeLA/assets/54461374/61d5aabf-b301-4cd2-a55f-fe96bab78348">
<img width="462" alt="屏幕截图 2023-10-20 161313" src="https://github.com/Matrix-ASC/DeLA/assets/54461374/f75146a3-06f9-48c0-99c2-4e61d6d4ddb1">

I would like to know how **downsampling ratio** was determined and how it relates to **grid size**.

**Comment by binjiechen** [comment]
Hi, grid subsampling picks one point in each grid.  A larger grid size leads to smaller grids and thus a higher downsampling ratio (original / downsampled points).
The actual downsampling ratio depends on the data. I simply load some point clouds, grid sample (leaving hash_size to 1) them, and print the ratios, then determine one.
This parameter setting is mainly for performance issues. It's been quite some time since I wrote it and I can't recall its impact. But it should be minor. 
Just don't set it too small, in which case the hash table can't accommodate all subsampled points and a runtime error can occur.
